### PR TITLE
Add Tradedoubler to redirects

### PR DESCRIPTION
**Pull request by jarettmillard**
Does what it says on the tin. Tradedoubler has a ton of tracking methods, but this should catch most, if not all, of their outbound tracking links.

### CODE REVIEW

**Comment by newhouse** [comment]
Hey @jarettmillard thanks for the PR! I just added this to the README right now, but would you mind adding a few redirect examples to the `redirectExamples` array in the `examples.js` file, and make sure it passes the tests by running `npm test`?

Everything looks like it should be just fine, but I should have put that in the README sooner. Will merge right after if all that looks good.

Thanks again!

**Comment by jarettmillard** [comment]
Sure, no problem. I did peek into the `test` directory to see if you had test cases, but I missed the part where it included the examples. Oops.

**Comment by newhouse** [comment]
It's definitely a bit convoluted, so not your fault!

**Comment by newhouse** [comment]
hey @jarettmillard I didn't mean to stall this out and I'd love to get it in there.

Can you provide an example from-and-to URLs and I'll add them myself?!

Thanks,
 Chris

**Comment by jarettmillard** [comment]
Sorry, I just totally forgot about adding the examples after I said I would. Test case is added now.

**Comment by newhouse** [comment]
Thanks again so much for the contribution!

There are a couple things I'm noticing that I wanted to ask about:
1) The test is actually failing due to the blank key + values on the first query string parameter: `http://clkde.tradedoubler.com/click?=&p=...`. Is that something you actually found out in the wild like that? I can of course fix this in the example by adding a key + value, but I'm wondering if I should consider "fixing" this in the regex to support weirdness like that...or use some other system.
2) Your example uses `clkde.tradedoubler.com` as the domain, and the pattern you created specifies `${SCHEMA}${SUBDOMAIN}.tradedoubler.com/click?`. I'm just making sure if that `${SUBDOMAIN}` is necessary, or if it should be hard-coded as `${SCHEMA}clkde.tradedoubler.com/click?` in order to save regex steps. If you've seen more than 1 subdomain for this redirect, then the way you have it is correct (and I'd ask that you add 1 more real example if you can?)

Thanks again!

**Comment by jarettmillard** [comment]
1) Yes, I did find it in the wild like that. I updated the regex to account for that as well. Is the test still failing with the fix? https://github.com/newhouse/url-tracking-stripper/blob/913e0b0dd98ec775fc03afcf1405f907c164ed53/assets/js/redirects.js
2) I've seen other tradedoubler.com links with different subdomains. I looked around a bit to try to determine if they use randomized subdomains, but I couldn't tell one way or another so I figured it would be better to use the wildcard.

**Comment by newhouse** [comment]
1. I'm not seeing that regex change as part of the PR anymore (maybe overwritten by merge). Or maybe I'm taking crazy pills? Either way, I was working a similar fix for that...
2) Cool, thanks

**Comment by newhouse** [comment]
thanks for the contribution!

**Comment by jarettmillard** [comment]
Weird, it doesn't show up as part of the PR for me either but it does show up when I look at the commit. Maybe something weird happened when I made the merge commit.

Either way, you're welcome!

**Comment by jarettmillard** [comment]
Just FYI for the querystring matching, `...?=&...`, `...?&...`, and `...?foo&...` are all valid.

**Comment by newhouse** [comment]
Hmm, I suppose this means that my regex is incorrect then and needs the optional `=` (e.g. `=?`) that you had in yours?

**Comment by jarettmillard** [comment]
That's why I added the `?`, yes.

**Comment by newhouse** [comment]
The internet is an ugly world! Thanks man, I'll add that in...

**Comment by jarettmillard** [comment]
No problem.

**Pull request merged**
